baseURL: https://johnnaliu-portfolio.netlify.app/
languageCode: en-us
title: Portfolio website from Johnna Liu for Kostis
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Brought up in China, I have studied and lived across China, the US and the UK. I am currently reading for the MFA2022 at LBS.  
      Prior, I majored in media studies and graduated earlier this year from Fudan University.
    title: Hi, my name is Johnna Liu.
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: 1 Palgrave Gardens
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: johnnal.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (44) 7951 034553 
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      #- icon: fa-twitter
        #label: Twitter
        #url: https://www.twitter.com
      #- icon: fa-facebook
        #label: Facebook
        #url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/johnnaliuuu/
      - icon: fa-github
        label: GitHub
        url: https://github.com/JohnnaLiu
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/johnnaliu/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      #- name: Generic Blog
        #url: blogs/ipsum
      #- name: Elements
        #url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: Johnna.jpg
        subtitle: Facts about me
        title: Self Introduction
        url: blogs/blog1
      - image: Fudan.jpg
        subtitle: My undergrad
        title: Fudan University
        url: https://www.fudan.edu.cn/en/
      - image: lbs.jpg
        subtitle: Risk-Return of DJIA stocks
        title: Stock Analysis
        url: blogs/risk_return
      #- image: pic04.jpg
        #subtitle: Nisl Sed Aliquam
        #title: Ipsum
        #url: blogs/ipsum
      #- image: pic05.jpg
        #subtitle: Ipsum Dolor Sit Amet
        #title: Consequat
        #url: blogs/ipsum
      #- image: pic06.jpg
        #subtitle: Feugiat Amet Tempus
        #title: Etiam
        #url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "
    I explored a lot during my college years including research assistant, non-profit organization, fashion start-up, consulting, venture capital, investment banking, private equity and pre-IPO technology company.
      \n  Those diverse experiences helped me figure out who I am and who I want to become. I eventually decide to choose entreprenurship as my life-long career.
      \n  I have strong passion towards frontier technology especially AI, ML and VR, and I do buy in the future of metaverse.
      \n  Recently I am learning to play squash, golf and snowboarding.
      \n  Feel free to contact me if we have something in common to have deep conversation. ;p "
    title: Fun facts about me
    url: http://www.xwxy.fudan.edu.cn/n1339/index.html/
